# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('googleAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAuthCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GoogleAuthCodes',
                'verbose_name': 'Google auth code',
                'verbose_name_plural': 'Google auth codes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='googleauthcodes',
            unique_together=set([('user', 'code')]),
        ),
    ]
